### PR TITLE
Trovi 2.0: Adapt upload flow to upload to Trovi API instead of Swift

### PR DESCRIPTION
**Pull request by super-cooper**
Change artifact upload content headers to match new mime type of tar+gz

### CODE REVIEW

**Comment by super-cooper** [comment]
[Trovi 2.0: Adapt upload flow to upload to Trovi API instead of Swift](https://trello.com/c/i8tEocpz/2540-trovi-20-adapt-upload-flow-to-upload-to-trovi-api-instead-of-swift)

**Review by diurnalist — APPROVED** [review]
Looks very straightforward! It may make sense to start transitioning the language around "deposition" to "contents" to match the new nomenclature.

**Comment by super-cooper** [comment]
I agree with your thoughts on "deposition;" however, there are no changes which use that word in this patch. Were you looking at the `content-disposition` header? 

Regardless, I think I'm going to hotfix the deposition ID out of my jupyterhub patch, because, you're right, it's no longer needed.

**Comment by diurnalist** [comment]
@super-cooper you're right, you didn't add any references to it, I just noticed it in code around these changes and thought we should over time fix that up so it's more consistent.

**Comment by super-cooper** [comment]
> @super-cooper you're right, you didn't add any references to it, I just noticed it in code around these changes and thought we should over time fix that up so it's more consistent.

Good idea. I've pushed another commit to fix that

**Review by diurnalist — APPROVED** [review]

**Pull request merged**
