### PR TITLE
Store artifact location during database initialization.

### PR DESCRIPTION
**Pull request by super-cooper**

### CODE REVIEW

**Comment by super-cooper** [comment]
[Fix ownership of artifact when launched via trovi](https://trello.com/c/gz59tuXg/2779-fix-ownership-of-artifact-when-launched-via-trovi)

**Review by Mark-Powers — COMMENTED** [review]
I think this looks right in theory, but I'm not understanding the comment.

So when launching, I think the steps are like:
1. clone to /tmp/artifact or whatever
2. copy those files to /home/work

I can see why setting path to "" would probably not work, but
is this inserting it with the right final path? As in it properly shows
the dir as linked?

**Review by Mark-Powers — APPROVED** [review]
ah I think I see based on the other PR, ARTIFACT_DIR_NAME_FILE is the name of the artifact, and so `/home/work/$ARTIFACT_DIR_NAME_FILE` will be the artifact in the DB, right? Is there a case where an artifact doesn't have a root directory, and instead is just a bunch of files? That's my only question, but otherwise this looks like a great fix.

**Comment by super-cooper** [comment]
All the change in https://github.com/ChameleonCloud/jupyterhub-deploy does is store the name of the root dir of the artifact in a file in tmp. 

The change in this repo reads that file, and stores the correct path in the database at start.

**Comment by Mark-Powers** [comment]
Is there a reason the name is stored in a file instead of an environment variable? Storing it in a file seems to add a layer of indirection.

**Comment by super-cooper** [comment]
The environment variable was not persisted between script runs. I was unsure if it was possible to somehow edit docker's environment config so that every environment would see it.

**Comment by Mark-Powers** [comment]
I'm confused then how ARTIFACT_OWNERSHIP is being set, since that is also an env that I think is set in the same place, that is inserted into the DB.

**Comment by super-cooper** [comment]
That variable is inserted into the docker environment by JupyterHub, and its value comes from the URL parameters from the incoming request from portal

```
(portal) ?ownership=own -> (jupyterhub) artifact.ownership -> (jupyterhub) env["ARTIFACT_OWNERSHIP"] -> (jupyterlab) $ARTIFACT_OWNERSHIP
```

**Comment by Mark-Powers** [comment]
OK, this is a good solution, but I'm just concerned this adds one more layer that we'll have to piece together next time we need to fix something. Could you add a section to the Jupyter operator gitbook about how loading an artifact works mentioning this? That should help us in case anything comes up.

**Comment by super-cooper** [comment]
I agree that it is concerning, and I disagree that it is a good solution :P It does work though. 

I was originally trying to get this variable in from Portal, but struggled to find a way to do it without either downloading the archive in portal to read the name, or modifying the Trovi API. In reality, this should probably be stored in Trovi so that other clients are not forced to adopt our exact linking scheme.

**Comment by Mark-Powers** [comment]
I don't think we should store it in Trovi, that seems like an implementation detail of how clients manage artifacts and versions. To me, it seems like the issues are more so how our Jupyterlab works with artifacts.

**Pull request merged**
